apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app
        image: healthcare-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000